version: 2
updates:
  # Monitor npm dependencies for actions/validate-commit
  - package-ecosystem: "npm"
    directory: "/actions/validate-commit"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Monitor npm dependencies for actions/setup-branching-strategy
  - package-ecosystem: "npm"
    directory: "/actions/setup-branching-strategy"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Monitor npm dependencies for actions/prevent-committer-approval
  - package-ecosystem: "npm"
    directory: "/actions/prevent-committer-approval"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Monitor npm dependencies for actions/validate-branch-promotion
  - package-ecosystem: "npm"
    directory: "/actions/validate-branch-promotion"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Monitor npm dependencies for actions/derive-next-version
  - package-ecosystem: "npm"
    directory: "/actions/derive-next-version"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Monitor npm dependencies for actions/action-approval-gate
  - package-ecosystem: "npm"
    directory: "/actions/action-approval-gate"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Monitor GitHub Actions workflow versions in .github/workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      actions:
        patterns:
          - "*"
